swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <img src='#' onerror='fetch("/etc/passwd").then(r=>r.text()).then(d=>alert(d))'>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
